name: Vercel Env Upsert
description: Upsert env vars to Vercel
author: thomasgrastein

branding:
  icon: anchor
  color: gray-dark

inputs:
  VARS:
    required: true
    description: Supports several
  VERCEL_TOKEN:
    required: true
  VERCEL_ORG_ID:
    required: true
  VERCEL_PROJECT_ID:
    required: true
  TYPE:
    default: 'plain'
  TARGET:
    default: 'preview'
  GIT_BRANCH:

runs:
  using: node20
  main: dist/index.js
